### ISSUE TITLE
error code: {f'{-hr:02x}'}

### ISSUE THREAD

**Issue by pccctoa** [lovettchris/wincam#9]
Hi, Thank you for your products. It work perfectly on window 11, python 3.12
But i'm very newbie and when i try example code on window 10 build 10.0.1942 and python 3.12.7, Visual code 1.77.3; i get error:
PS C:\Users\Administrator> & C:/Users/Administrator/anaconda3/python.exe "c:/Users/Administrator/from wincam import DXCamera.py"
Capture failed -2147467262
Traceback (most recent call last):
  File "c:\Users\Administrator\from wincam import DXCamera.py", line 5, in <module>
    frame, timestamp = camera.get_bgr_frame()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\Lib\site-packages\wincam\dxcam.py", line 58, in get_bgr_frame
    raise Exception(f"Failed to start capture, error code {f'{-hr:02x}'}")
Exception: Failed to start capture, error code 7fffbffe
PS C:\Users\Administrator> 
i tried with dxcam, it worked.

**Comment by lovettchris** [comment]
Yes, others have reported problems with Windows 10 also, I should probably just remove that from the list of supported operating systems. I recommend moving to windows 11.

**Comment by pccctoa** [comment]
The error occurred with the electronic store computer system, when the machines were set to freeze the hard drive to reset each time it was restarted. At the same time, it cannot run with the highest Admin rights; As for personal computers with Windows 11 installed, it's normal. Thank you! ^^
